# Generated by Django 6.0.6 on 2026-06-27 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del anuncio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (S/.)')),
                ('distrito', models.CharField(choices=[('campo_verde', 'Campo Verde'), ('pucallpa', 'Pucallpa'), ('honoria', 'Honoria'), ('tournavista', 'Tournavista'), ('nueva_requena', 'Nueva Requena'), ('neshuya', 'Neshuya')], default='pucallpa', max_length=20)),
                ('categoria', models.CharField(choices=[('casas', 'Venta y Alquiler de Casas'), ('artefactos', 'Artefactos Eléctricos'), ('vehiculos', 'Vehículos'), ('otros', 'Otros productos')], default='otros', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
