# Generated by Django 6.0.6 on 2026-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_anuncio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPublicitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Nombre del Cliente/Negocio')),
                ('imagen', models.ImageField(upload_to='banners/', verbose_name='Banner Horizontal (Recomendado 1200x300)')),
                ('enlace_whatsapp', models.URLField(blank=True, null=True, verbose_name='Enlace de WhatsApp o Web (Opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en la página?')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.CharField(choices=[('casas', 'Lotes, Casas y Terreno'), ('artefactos', 'Artefactos Eléctricos'), ('vehiculos', 'Vehículos'), ('otros', 'Otros productos')], default='otros', max_length=20),
        ),
    ]
